In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [23]:
### Data input
pop_df = pd.read_csv('../../data/raw/ACSST5Y2020.S2301_data_with_overlays_2022-04-11T134445.csv', skiprows = 1) # population and employment rate

In [24]:
pop_df

,id,Geographic Area Name,Estimate!!Total!!Population 16 years and over,Margin of Error!!Total!!Population 16 years and over,Estimate!!Total!!Population 16 years and over!!AGE!!16 to 19 years,Margin of Error!!Total!!Population 16 years and over!!AGE!!16 to 19 years,Estimate!!Total!!Population 16 years and over!!AGE!!20 to 24 years,Margin of Error!!Total!!Population 16 years and over!!AGE!!20 to 24 years,Estimate!!Total!!Population 16 years and over!!AGE!!25 to 29 years,Margin of Error!!Total!!Population 16 years and over!!AGE!!25 to 29 years,...,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years,Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate,Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency),Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency),Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree,Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher,Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher
0,310M600US10100,"Aberdeen, SD Micro Area",33829,246,2355,181,3087,258,2834,252,...,2.2,0.8,1.1,1.5,4.1,2.4,1.9,1.3,1.2,0.9
1,310M600US10140,"Aberdeen, WA Micro Area",60437,171,3158,247,3549,163,4476,206,...,5.6,1.2,12.2,5.3,7.4,2.6,4.1,1.4,2.7,1.7
2,310M600US10180,"Abilene, TX Metro Area",135054,297,9901,360,16104,274,13621,201,...,2.6,0.5,4.0,2.1,3.1,0.8,3.4,1.1,0.8,0.5
3,310M600US10220,"Ada, OK Micro Area",30190,97,2221,127,3108,119,2751,60,...,4.5,1.1,6.3,3.5,5.4,2.4,5.8,2.2,2.3,1.3
4,310M600US10300,"Adrian, MI Micro Area",80033,190,5113,224,6432,163,5756,175,...,4.4,0.7,9.0,4.7,6.1,1.7,3.2,0.9,2.8,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,310M600US49660,"Youngstown-Warren-Boardman, OH-PA Metro Area",444105,455,26288,486,32916,227,32346,158,...,5.4,0.4,12.6,2.8,6.2,0.7,5.2,0.8,3.1,0.7
935,310M600US49700,"Yuba City, CA Metro Area",132221,313,8872,368,11325,232,13556,186,...,6.2,0.9,10.7,2.8,5.0,1.3,7.0,2.0,3.2,1.1
936,310M600US49740,"Yuma, AZ Metro Area",164420,371,12040,406,17631,257,15630,281,...,7.1,0.9,14.2,2.8,7.0,1.8,4.9,1.1,3.8,1.6
937,310M600US49780,"Zanesville, OH Micro Area",68618,206,4169,231,5567,166,5456,123,...,4.5,1.0,9.5,6.8,6.2,1.7,4.2,1.2,1.0,0.9
938,310M600US49820,"Zapata, TX Micro Area",9956,155,819,202,1105,131,912,30,...,5.3,3.1,9.5,7.5,6.9,6.4,0.6,1.1,1.5,2.4

In [25]:
len(pop_df)

939

In [26]:
pop_df.columns

Index(['id', 'Geographic Area Name',
       'Estimate!!Total!!Population 16 years and over',
       'Margin of Error!!Total!!Population 16 years and over',
       'Estimate!!Total!!Population 16 years and over!!AGE!!16 to 19 years',
       'Margin of Error!!Total!!Population 16 years and over!!AGE!!16 to 19 years',
       'Estimate!!Total!!Population 16 years and over!!AGE!!20 to 24 years',
       'Margin of Error!!Total!!Population 16 years and over!!AGE!!20 to 24 years',
       'Estimate!!Total!!Population 16 years and over!!AGE!!25 to 29 years',
       'Margin of Error!!Total!!Population 16 years and over!!AGE!!25 to 29 years',
       ...
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years',
       'Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate',
       'Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)',
       'Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree',
       'Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree',
       'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher',
       'Margin of Error!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher'],
      dtype='object', length=282)

In [27]:
#pop_df.loc[: , (pop_df != 'Margin of Error').all()]
filtered_cols = [col for col in pop_df.columns if 'Margin of Error' not in col]
filtered_cols = [col for col in filtered_cols if 'SEX' not in col]
filtered_cols = [col for col in filtered_cols if 'RACE' not in col]
filtered_cols = [col for col in filtered_cols if 'Percent' not in col]
filtered_cols

['id',
 'Geographic Area Name',
 'Estimate!!Total!!Population 16 years and over',
 'Estimate!!Total!!Population 16 years and over!!AGE!!16 to 19 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!20 to 24 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!25 to 29 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!30 to 34 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!35 to 44 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!45 to 54 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!55 to 59 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!60 to 64 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!65 to 74 years',
 'Estimate!!Total!!Population 16 years and over!!AGE!!75 years and over',
 'Estimate!!Total!!Population 20 to 64 years',
 'Estimate!!Total!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!Below poverty level',
 'Estimate!!Total!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!At or above the poverty level',
 'Estimate!!Total!!Population 20 to 64 years!!DISABILITY STATUS!!With any disability',
 'Estimate!!Total!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years',
 'Estimate!!Total!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate',
 'Estimate!!Total!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)',
 "Estimate!!Total!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree",
 "Estimate!!Total!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher",
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!16 to 19 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!20 to 24 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!25 to 29 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!30 to 34 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!35 to 44 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!45 to 54 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!55 to 59 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!60 to 64 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!65 to 74 years',
 'Estimate!!Labor Force Participation Rate!!Population 16 years and over!!AGE!!75 years and over',
 'Estimate!!Labor Force Participation Rate!!Population 20 to 64 years',
 'Estimate!!Labor Force Participation Rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!Below poverty level',
 'Estimate!!Labor Force Participation Rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!At or above the poverty level',
 'Estimate!!Labor Force Participation Rate!!Population 20 to 64 years!!DISABILITY STATUS!!With any disability',
 'Estimate!!Labor Force Participation Rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years',
 'Estimate!!Labor Force Participation Rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate',
 'Estimate!!Labor Force Participation Rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)',
 "Estimate!!Labor Force Participation Rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree",
 "Estimate!!Labor Force Participation Rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher",
 'Estimate!!Employment/Population Ratio!!Population 16 years and over',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!16 to 19 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!20 to 24 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!25 to 29 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!30 to 34 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!35 to 44 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!45 to 54 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!55 to 59 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!60 to 64 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!65 to 74 years',
 'Estimate!!Employment/Population Ratio!!Population 16 years and over!!AGE!!75 years and over',
 'Estimate!!Employment/Population Ratio!!Population 20 to 64 years',
 'Estimate!!Employment/Population Ratio!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!Below poverty level',
 'Estimate!!Employment/Population Ratio!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!At or above the poverty level',
 'Estimate!!Employment/Population Ratio!!Population 20 to 64 years!!DISABILITY STATUS!!With any disability',
 'Estimate!!Employment/Population Ratio!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years',
 'Estimate!!Employment/Population Ratio!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate',
 'Estimate!!Employment/Population Ratio!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)',
 "Estimate!!Employment/Population Ratio!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree",
 "Estimate!!Employment/Population Ratio!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher",
 'Estimate!!Unemployment rate!!Population 16 years and over',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!16 to 19 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!20 to 24 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!25 to 29 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!30 to 34 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!35 to 44 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!45 to 54 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!55 to 59 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!60 to 64 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!65 to 74 years',
 'Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!75 years and over',
 'Estimate!!Unemployment rate!!Population 20 to 64 years',
 'Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!Below poverty level',
 'Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!At or above the poverty level',
 'Estimate!!Unemployment rate!!Population 20 to 64 years!!DISABILITY STATUS!!With any disability',
 'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years',
 'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate',
 'Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency)',
 "Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree",
 "Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher"]

In [28]:
#len(pop_df)

In [29]:
pop_df = pop_df.filter(filtered_cols)

In [30]:
pop_df.head()

,id,Geographic Area Name,Estimate!!Total!!Population 16 years and over,Estimate!!Total!!Population 16 years and over!!AGE!!16 to 19 years,Estimate!!Total!!Population 16 years and over!!AGE!!20 to 24 years,Estimate!!Total!!Population 16 years and over!!AGE!!25 to 29 years,Estimate!!Total!!Population 16 years and over!!AGE!!30 to 34 years,Estimate!!Total!!Population 16 years and over!!AGE!!35 to 44 years,Estimate!!Total!!Population 16 years and over!!AGE!!45 to 54 years,Estimate!!Total!!Population 16 years and over!!AGE!!55 to 59 years,...,Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!75 years and over,Estimate!!Unemployment rate!!Population 20 to 64 years,Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!Below poverty level,Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!At or above the poverty level,Estimate!!Unemployment rate!!Population 20 to 64 years!!DISABILITY STATUS!!With any disability,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency),Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher
0,310M600US10100,"Aberdeen, SD Micro Area",33829,2355,3087,2834,2726,4678,4763,2851,...,1.6,2.2,5.1,2.0,11.4,2.2,1.1,4.1,1.9,1.2
1,310M600US10140,"Aberdeen, WA Micro Area",60437,3158,3549,4476,4354,8574,8883,5196,...,0.0,6.2,27.1,4.2,11.9,5.6,12.2,7.4,4.1,2.7
2,310M600US10180,"Abilene, TX Metro Area",135054,9901,16104,13621,12125,20479,17530,10169,...,2.4,3.0,8.7,2.5,5.8,2.6,4.0,3.1,3.4,0.8
3,310M600US10220,"Ada, OK Micro Area",30190,2221,3108,2751,2501,4493,4238,2057,...,0.0,5.1,18.9,4.0,8.7,4.5,6.3,5.4,5.8,2.3
4,310M600US10300,"Adrian, MI Micro Area",80033,5113,6432,5756,5495,11617,12990,6827,...,1.9,4.3,14.1,3.6,8.1,4.4,9.0,6.1,3.2,2.8

In [31]:
pop_df = pop_df.set_index('Geographic Area Name')
pop_df = pop_df.filter(like="Metro Area", axis = 0)
pop_df.index = pop_df.index.str.replace(' Metro Area', '')

In [32]:
pop_df.head()

,id,Estimate!!Total!!Population 16 years and over,Estimate!!Total!!Population 16 years and over!!AGE!!16 to 19 years,Estimate!!Total!!Population 16 years and over!!AGE!!20 to 24 years,Estimate!!Total!!Population 16 years and over!!AGE!!25 to 29 years,Estimate!!Total!!Population 16 years and over!!AGE!!30 to 34 years,Estimate!!Total!!Population 16 years and over!!AGE!!35 to 44 years,Estimate!!Total!!Population 16 years and over!!AGE!!45 to 54 years,Estimate!!Total!!Population 16 years and over!!AGE!!55 to 59 years,Estimate!!Total!!Population 16 years and over!!AGE!!60 to 64 years,...,Estimate!!Unemployment rate!!Population 16 years and over!!AGE!!75 years and over,Estimate!!Unemployment rate!!Population 20 to 64 years,Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!Below poverty level,Estimate!!Unemployment rate!!Population 20 to 64 years!!POVERTY STATUS IN THE PAST 12 MONTHS!!At or above the poverty level,Estimate!!Unemployment rate!!Population 20 to 64 years!!DISABILITY STATUS!!With any disability,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Less than high school graduate,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!High school graduate (includes equivalency),Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Some college or associate's degree,Estimate!!Unemployment rate!!EDUCATIONAL ATTAINMENT!!Population 25 to 64 years!!Bachelor's degree or higher
Geographic Area Name,,,,,,,,,,,,,,,,,,,,,
"Abilene, TX",310M600US10180,135054,9901,16104,13621,12125,20479,17530,10169,9291,...,2.4,3.0,8.7,2.5,5.8,2.6,4.0,3.1,3.4,0.8
"Aguadilla-Isabela, PR",310M600US10380,248419,15364,19280,18808,16611,36422,39449,20021,20970,...,3.5,15.5,31.1,6.5,21.8,13.3,20.4,16.9,13.0,7.9
"Akron, OH",310M600US10420,577639,38652,51424,47928,42959,80391,91465,51488,49566,...,2.6,5.3,24.0,3.7,11.8,5.0,11.3,7.2,4.7,2.7
"Albany, GA",310M600US10500,115842,8563,10460,10093,9344,17510,17656,9334,9449,...,3.8,7.5,28.0,4.0,20.8,6.4,16.5,7.6,5.6,2.4
"Albany-Lebanon, OR",310M600US10540,101876,6006,7246,8765,8351,15293,15127,8751,8694,...,8.3,6.7,27.1,5.0,14.5,6.2,7.3,7.5,6.8,2.9

In [33]:
### Create empty dataframe with ACS MSA names as index:
#po_df = pd.DataFrame(index = pop_df.index)

In [34]:
employment_rate = pop_df['Estimate!!Employment/Population Ratio!!Population 16 years and over']

In [35]:
employment_rate

Geographic Area Name
Abilene, TX                          56.1
Aguadilla-Isabela, PR                32.5
Akron, OH                            61.0
Albany, GA                           53.1
Albany-Lebanon, OR                   55.3
                                     ...
Yauco, PR                            29.6
York-Hanover, PA                     62.7
Youngstown-Warren-Boardman, OH-PA    53.5
Yuba City, CA                        52.9
Yuma, AZ                             47.9
Name: Estimate!!Employment/Population Ratio!!Population 16 years and over, Length: 392, dtype: float64

In [36]:
unemployment_rate_check = 100 - employment_rate

In [37]:
unemployment_rate_check

Geographic Area Name
Abilene, TX                          43.9
Aguadilla-Isabela, PR                67.5
Akron, OH                            39.0
Albany, GA                           46.9
Albany-Lebanon, OR                   44.7
                                     ...
Yauco, PR                            70.4
York-Hanover, PA                     37.3
Youngstown-Warren-Boardman, OH-PA    46.5
Yuba City, CA                        47.1
Yuma, AZ                             52.1
Name: Estimate!!Employment/Population Ratio!!Population 16 years and over, Length: 392, dtype: float64

In [38]:
#Does not match unemployment check

unemployment_rate = pop_df['Estimate!!Unemployment rate!!Population 16 years and over']

In [39]:
unemployment_rate

Geographic Area Name
Abilene, TX                           3.3
Aguadilla-Isabela, PR                15.8
Akron, OH                             5.8
Albany, GA                            8.5
Albany-Lebanon, OR                    6.8
                                     ...
Yauco, PR                            21.9
York-Hanover, PA                      4.6
Youngstown-Warren-Boardman, OH-PA     6.4
Yuba City, CA                         7.4
Yuma, AZ                              8.6
Name: Estimate!!Unemployment rate!!Population 16 years and over, Length: 392, dtype: float64

In [40]:
pop_df.to_csv('data-aggregation-pop.csv', index = False)